### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by Dreamer-Paul** [Dreamer-Paul/Hingle#1]
此处列出主题接下来会陆陆续续增加的一些功能，做个备忘：

- [ ] Gallery Post 文章不支持 `photos` 字段
- [ ] Tag Plugins 文章不支持 With caption 模式
- [ ] 奇趣框架的 `em` 元素应该是斜体
- [x] word-break: break-word; 从 break-all 替换过来（两个主题都需要改）
- [ ] 不支持百度以外的搜索功能
- [ ] 不支持预设评论组件引入
- [ ] 夜间模式的 Bug（替换成根据系统适配）

**Comment by hifocus** [comment]
~我的海报呢？！我的海报呢？！~

**Comment by 70loKirin** [comment]
# 评论组组件

非常感谢你的主题，我一直在使用，但是近来感觉没有评论区还是不太好，所以自行查找了一些方法，但是个人水平较差，遇到了一个问题，来请教一下

---
我使用的的是[giscus](https://giscus.app/zh-CN)配置起来很方便，最终只要将一个<script>标签加入就行了

![image](https://user-images.githubusercontent.com/91271243/218241014-367ef745-e9a1-4d66-b7c3-6dda4661e7c9.png)
![image](https://user-images.githubusercontent.com/91271243/218241035-729422a7-4665-40fe-ade7-94a6abd8d97b.png)
![image](https://user-images.githubusercontent.com/91271243/218241040-f609777a-47c9-4777-a6eb-3ec4cd0652fd.png)
但是我只明白像这样直接添加进一个HTML文件中可以达到这样的效果，请问我应该如何修改您的主题文件使得每个文章页自动添加此<script>标签？

（网页编程这块我没太学习过，如果您觉得目前我改动起来难度较大，那我学习之后再研究研究）

**Comment by Dreamer-Paul** [comment]
> # 评论组组件
> 非常感谢你的主题，我一直在使用，但是近来感觉没有评论区还是不太好，所以自行查找了一些方法，但是个人水平较差，遇到了一个问题，来请教一下
> 
> 我使用的的是[giscus](https://giscus.app/zh-CN)配置起来很方便，最终只要将一个<script>标签加入就行了
> 
> ![image](https://user-images.githubusercontent.com/91271243/218241014-367ef745-e9a1-4d66-b7c3-6dda4661e7c9.png) ![image](https://user-images.githubusercontent.com/91271243/218241035-729422a7-4665-40fe-ade7-94a6abd8d97b.png) ![image](https://user-images.githubusercontent.com/91271243/218241040-f609777a-47c9-4777-a6eb-3ec4cd0652fd.png) 但是我只明白像这样直接添加进一个HTML文件中可以达到这样的效果，请问我应该如何修改您的主题文件使得每个文章页自动添加此<script>标签？
> 
> （网页编程这块我没太学习过，如果您觉得目前我改动起来难度较大，那我学习之后再研究研究）

在 `post.ejs` 的 [这个位置](https://github.com/Dreamer-Paul/Hingle/blob/main/layout/post.ejs#L46) 下面增加应该就可以，主题后续应该会提供多种评论备选方案才比较科学，因为已经有现成的主题实现了类似的功能了，只是我一直没空继续调查研究

**Comment by 70loKirin** [comment]
感谢，现在弄好了
